language: python

services:
  - docker

python:
  - "2.7"

addons:
  apt:
    packages:
    - pylint

stages:
  - Linting
  - test

install:
  - python setup.py install

jobs:
  include:
    - stage: Linting
      script: helloworld_in_python
    - stage: test
      script: helloworld_in_python

dist: trusty
